### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] set `body` background to green for grass
- [x] create an `img` element with `id="car"`
- [x] size the `#car` to a reasonable amount
