### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/driving-game#2]
https://github.com/Learning-Fuze/driving-game-instructions/blob/main/features/user-can-turn-their-car.md

## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] CSS: set transition property of `#car` targetting transform property

- [x] Grab `#car` in DOM and set to variable. 

- [x] Create object constructor `Car` with `direction` property indicating direction based off of direction (number)
  - [x] `turn()` method that takes a number or string and sets appropriate value to `this.direction`
    - [x] Upon call, change `#car` transform rotateX according to value
    - [ ] NEW ISSUE: cars turn unrealistically from 270 to 0. Go beyond 360 if needed

- [x] Create new data model object `inputHandler` with properties of ingame controls (cardinal directions) and associated key and function

- example: `turnCarLeft: { key: 'arrowLeft', action: car.turn(180) };`

- [x] Create event handler function `inputListener(event)`, attach to event listener for `document` on event of `keydown`
  - [x] Iterate through `inputHandler` elements to see if `event.key` lines up with the keybind property of the event. Execute the associated function and return on match.
