### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/driving-game#3]
https://github.com/Learning-Fuze/driving-game-instructions/blob/main/features/user-can-start-their-car.md

## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add `gear` property to `Car` object. (0: neutral/parked, 1: accelerate)
- [x] add to `inputHandler`, spacebar, which calls `player.toggleGear` a new method ~~ toggles `player.gear` through new method `player.toggleGear` ~~
- [x] player.toggleGear activates interval with expression `Car.position.x += speed` every 16ms
- [x] add `speed` property to `Car` object, with value of amount of pixels to move per 16ms
- [x] add `position` property to `Car` object, which is an object with properties `x` and `y`
- [x] player.toggleGear activates interval with expression `Car.position.x += speed` every 16ms

~~ call setInterval every 16 ms to check if `Car.gear === 1`, assign return intervalID to `gameLoop` variable. ~~
~~ within game loop, if `Car.gear === 1`, then `Car.position.x += speed`, else pass. ~~

- [x] add `translate` CSS transform variable to `Car.update()` expression for `transform` property

~~ - [ ] move `Car.update()` call to `gameLoop` interval call.  ~~
