### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by jojobii-arks** [joseph-bravo/driving-game#4]
https://github.com/Learning-Fuze/driving-game-instructions/blob/main/features/user-can-stop-their-car.md

## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] change `Car.gear` so that it is a boolean to determine if car is moving or not
- [x] change `toggleGear` so that it will toggle the `Car.gear` boolean 
- [ ] new function `gameLoop`
- [ ] create variable `gameTimer`, `setInterval` that calls `gameLoop()` every 16ms
- [ ] `gameLoop()`, call `player.update()`
- [ ] in `player.update`, call `player.move` ONLY if `player.gear === 1`
